apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: frontend-nginx
  template:
    metadata:
      labels:
        name: frontend-nginx
    spec:
      containers:
      - name: frontend-nginx
        image: antony999k/colibri_webserver:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80