apiVersion: v1
kind: Service
metadata:
  name: frontend-nginx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  selector:
    name: frontend-nginx
  type: LoadBalancer