kind: Service
apiVersion: v1
metadata:
  name: nginx-frontend
  labels:
    name: nginx-frontend
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    name: nginx-frontend
  type: LoadBalancer