apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: neo4j-set
spec:
  selector:
    matchLabels:
      app: neo4j
  serviceName: "neo4j"
  replicas: 3
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: "neo4j:3.3.2-enterprise"
        imagePullPolicy: "IfNotPresent"
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "standard"
        resources:
          requests:
            storage: "1Gi"
